name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        auto-update-conda: true

    - name: Initialize conda
      run: |
        conda init bash
        source ~/.bashrc

    - name: Remove existing environment if it exists
      run: |
        conda env remove -n kaldi_asr || echo "Environment does not exist"

    - name: Create conda environment
      run: conda env create -f environment.yml

    - name: Activate conda environment and run tests
      run: |
        conda activate kaldi_asr
        pytest
